import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import MasterLayout from "@/app/MasterLayout";

// Metadata configuration
export const metadata: Metadata = {
  title: "Shop.Co",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MasterLayout>
          <Navbar />
          {children}
          <Footer />
        </MasterLayout>
      </body>
    </html>
  );
}
